remote_theme: pmarsceill/just-the-docs
title: Lowlands Tactical Wiki
description: Lowlands Tactical Documentation
color_scheme: dark
aux_links:
  "GitHub Repository":
    - "https://github.com/Lowlands-Tactical/LT-Wiki"
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  suggest: true
show_downloads: true
just_the_docs:
  custom_css:
    - assets/css/custom.css
    - body,
      body .site-header,
      body .site-footer,
      body .site-nav,
      body .main-content {
        background-color: var(--color-background-primary) !important;
        color: var(--color-text-primary) !important;
      } 