title: My Documentation
description: A comprehensive documentation site
theme: just-the-docs
color_scheme: dark
aux_links:
  "GitHub Repository":
    - "https://github.com/yourusername/your-repo"
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  suggest: true
show_downloads: true 